version: "3.5"
services:
  node:
    ports:
      - "3000:3000"
      - "80:80"
    image: node:22-alpine
    working_dir: /srv/app
    command: >
      sh -c "npm install && npm run dev"
    volumes:
      - .:/srv/app
    networks:
      - boilerplate
volumes:
  cache:
    driver: local
networks:
  boilerplate:
    name: boilerplate
